# Generated by Django 5.0.1 on 2024-01-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default='2024-01-28'),
        ),
    ]
