# Generated by Django 5.0.1 on 2024-01-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_remove_event_user_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default='2024-01-29'),
        ),
    ]
